spring.application.name=dementia-care

#datasource (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/record
spring.datasource.username=postgres
spring.datasource.password=rootroot
spring.datasource.driver-class-name=org.postgresql.Driver

# 연결 풀 설정 (HikariCP)
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000

# PostgreSQL 연결 확인
spring.datasource.hikari.connection-test-query=SELECT 1

#mybatis
mybatis.mapper-locations=classpath:mapper/mapper-*.xml
mybatis.type-aliases-package=lx.project.dementia_care.entity
mybatis.configuration.map-underscore-to-camel-case=true

##log 로깅은 일단 비활성화 해뒀어요
#logging.level.org.springframework.web=trace
#logging.level.org.springframework.bean=debug
#logging.level.mapper-chat=debug

#스프링 시큐리티 임시 id/pw
spring.security.user.name=1
spring.security.user.password={noop}1

#### 아래의 내용은 tmap api 테스트용입니다 ###
# 서버 포트
server.port=8080

# Tmap API 설정
tmap.api.key=3EkdQeGupP3Y0mJO1SuVC31mEYHXemG4hJMIET47
tmap.api.base-url=https://apis.openapi.sk.com/tmap

# 로그 레벨 설정 (디버깅용)
logging.level.com.safezone.tmapdemo=DEBUG
logging.level.org.springframework.web.client=DEBUG

# Gemini
gemini.api.url=https://api.gemini.ai/v1/analyze
gemini.api.key=${GEMINI_API_KEY}